### ISSUE TITLE
Assoc declaration

### ISSUE THREAD

**Issue by dzove855** [ayosec/bash-builtins.rs#2]
Hello,

I would like to know how to set an associative array.
Example:

Instead of variables::set(test, tu)
I would like to do something like variables::set(test[testing], tu)

**Comment by ayosec** [comment]
Thanks for the suggestion!

> I would like to do something like variables::set(test[testing], tu)

I added some functions to set and get elements in both indexed and associative arrays.

```rust
variables::assoc_set("test", "testing", "tu"))?;

let value = variables::assoc_get("test", "testing"); // == Some(CStr("tu"))
```

I published [version 0.3](https://github.com/ayosec/bash-builtins.rs/releases/tag/v0.3.0) with the new functions.

I'm closing the issue. If you find any issue, or this is not what you need, please feel free to reopen it.
